# Generated by Django 5.0.6 on 2024-06-24 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='long_name',
        ),
        migrations.AddField(
            model_name='software',
            name='decommission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='implemented_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='software',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
