# Generated by Django 5.0.6 on 2024-05-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_category_company_location_status_equipment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
