# Generated by Django 5.0.6 on 2024-06-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_software_created_at_software_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='last_updated',
            new_name='last_updated_at',
        ),
    ]
