# Generated by Django 5.0.6 on 2024-05-31 16:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_company_email_alter_company_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquepmentRecord',
            new_name='EquipmentRecord',
        ),
    ]
