# Generated by Django 5.0.6 on 2024-06-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_rename_last_updated_software_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
