# Generated by Django 5.0.6 on 2024-06-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_rename_equepmentrecord_equipmentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
