# Generated by Django 5.0.6 on 2024-06-03 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_equipment_inventory_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='warranty_period',
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer', to='asset.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
