# Generated by Django 5.0.6 on 2024-06-03 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_remove_equipment_warranty_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_provider', to='asset.company'),
        ),
    ]
