# Generated by Django 5.0.6 on 2024-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_rename_last_updated_equipment_last_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='source_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
