# Generated by Django 5.0.6 on 2024-06-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_recordtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentrecord',
            name='name',
        ),
        migrations.AddField(
            model_name='equipmentrecord',
            name='record_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset.recordtype'),
            preserve_default=False,
        ),
    ]
