# Generated by Django 5.0.6 on 2024-06-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_equipmentrecordattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Equipment Record', 'verbose_name_plural': 'Equipment Records'},
        ),
    ]
