# Generated by Django 5.0.6 on 2024-06-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_alter_equipmentrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recordtype',
            options={'ordering': ['name']},
        ),
    ]
