# Generated by Django 5.0.6 on 2024-07-30 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_assetschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetSchedule',
            new_name='Schedule',
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['schedule_date'], 'verbose_name_plural': 'schedules'},
        ),
    ]
