# Generated by Django 5.0.6 on 2024-06-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_equipment_replacement_date_equipment_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
