# Generated by Django 5.0.6 on 2024-07-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_schedule_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='active',
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Actioned'), (2, 'Cancelled')], default=0),
        ),
    ]
