# Generated by Django 5.0.6 on 2024-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_remove_schedule_active_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Actioned', 'Actioned'), ('Cancelled', 'Cancelled')], default='Active', max_length=10),
        ),
    ]
