# Generated by Django 5.0.6 on 2024-08-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_alter_schedule_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'schedules'},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(choices=[('O', 'One-off'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('H', 'Half-yearly'), ('Y', 'Yearly')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='next_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('P', 'Planned'), ('C', 'Completed'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
    ]
