# Generated by Django 5.0.6 on 2024-06-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_alter_category_name_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
