# Generated by Django 5.0.6 on 2024-06-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_alter_equipment_inventory_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='porcurement_date',
            new_name='procurement_date',
        ),
    ]
