# Generated by Django 5.0.6 on 2024-06-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_rename_porcurement_date_equipment_procurement_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'companies'},
        ),
    ]
