# Generated by Django 5.0.6 on 2024-08-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_schedule_updated_at_schedule_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('C', 'Completed'), ('X', 'Cancelled')], default='A', max_length=1),
        ),
    ]
