# Generated by Django 5.0.6 on 2024-06-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0022_equipment_created_at_equipment_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_updated_by',
        ),
    ]
