# Generated by Django 5.0.6 on 2024-08-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0022_maintenancetask_maintenancerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.maintenancetype'),
        ),
    ]
