# Generated by Django 5.0.6 on 2024-08-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0023_maintenancetype_alter_maintenancetask_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancetype',
            options={'ordering': ['name']},
        ),
    ]
