# Generated by Django 5.0.6 on 2024-08-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0024_alter_maintenancetype_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancetask',
            old_name='type',
            new_name='group',
        ),
    ]
