# Generated by Django 5.0.6 on 2024-06-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0024_equipment_created_at_equipment_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='procurement_date',
            new_name='received_date',
        ),
    ]
