# Generated by Django 5.0.6 on 2024-08-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0025_rename_type_maintenancetask_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceType',
            new_name='MaintenanceTaskGroup',
        ),
    ]
