# Generated by Django 5.0.6 on 2024-08-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0026_rename_maintenancetype_maintenancetaskgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
