# Generated by Django 5.0.6 on 2024-06-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0026_calibration_equipment_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
