# Generated by Django 5.0.6 on 2024-08-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0027_maintenancetask_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'ordering': ['group', 'name']},
        ),
    ]
