# Generated by Django 5.0.6 on 2024-06-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0027_equipmenttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['name'], 'verbose_name_plural': 'equipment types'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name_plural': 'locations'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='asset.equipmenttype'),
            preserve_default=False,
        ),
    ]
