# Generated by Django 5.0.6 on 2024-08-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0028_alter_maintenancerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.equipmenttype'),
        ),
    ]
