# Generated by Django 5.0.6 on 2024-08-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0029_alter_maintenancetask_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceTaskGroup',
        ),
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'ordering': ['equipment_type', 'name']},
        ),
        migrations.RenameField(
            model_name='maintenancetask',
            old_name='group',
            new_name='equipment_type',
        ),
    ]
