# Generated by Django 5.0.6 on 2024-06-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0030_alter_license_options_software_softwareattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SofewareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
