# Generated by Django 5.0.6 on 2024-08-17 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0030_delete_maintenancetaskgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecordassignment',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='asset.maintenancerecord'),
        ),
        migrations.AlterField(
            model_name='maintenancerecordassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='asset.maintenancetask'),
        ),
    ]
