# Generated by Django 5.0.6 on 2024-08-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0031_alter_maintenancerecordassignment_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
