# Generated by Django 5.0.6 on 2024-06-20 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0031_sofewaretype'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='software_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='asset.sofewaretype'),
            preserve_default=False,
        ),
    ]
