# Generated by Django 5.0.6 on 2024-06-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0032_software_software_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='deprecated',
            new_name='active',
        ),
    ]
