# Generated by Django 5.0.6 on 2024-06-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0033_rename_deprecated_software_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='long_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
