# Generated by Django 5.0.6 on 2024-08-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0033_maintenancetask_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maintenancerecord',
            unique_together={('date', 'equipment')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenancerecordassignment',
            unique_together={('maintenance', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenancetask',
            unique_together={('name', 'equipment_type')},
        ),
    ]
