# Generated by Django 5.0.6 on 2024-06-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0034_software_long_name_alter_software_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SofewareType',
            new_name='SoftwareType',
        ),
    ]
