# Generated by Django 5.0.6 on 2024-08-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0034_alter_maintenancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecordassignment',
            options={'ordering': ['task', 'maintenance']},
        ),
    ]
