# Generated by Django 5.0.6 on 2024-08-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0036_maintenancerecordmenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecordmenu',
            options={'ordering': ['equipment_type']},
        ),
        migrations.AlterUniqueTogether(
            name='maintenancerecordmenu',
            unique_together={('equipment_type', 'link_text')},
        ),
    ]
