# Generated by Django 5.0.6 on 2024-08-18 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0037_alter_maintenancerecordmenu_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maintenancerecord',
            unique_together=set(),
        ),
    ]
