# Generated by Django 5.0.6 on 2024-08-19 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0038_alter_maintenancerecord_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maintenancerecordmenu',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='color',
            field=models.CharField(default='#EEEEEE', max_length=7),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type', 'status'], name='asset_equip_equipme_8653b0_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type'], name='asset_equip_equipme_1849a0_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='asset_equip_status__3286c6_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['equipment', 'date'], name='asset_maint_equipme_8d9397_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['equipment'], name='asset_maint_equipme_910b13_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['date'], name='asset_maint_date_3f5ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecordmenu',
            index=models.Index(fields=['equipment_type', 'link_text', 'link_icon'], name='asset_maint_equipme_54c83e_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecordmenu',
            constraint=models.UniqueConstraint(fields=('equipment_type', 'link_text'), name='unique_link_text'),
        ),
    ]
