# Generated by Django 5.0.9 on 2024-11-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0039_alter_maintenancerecordmenu_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtype',
            name='color',
            field=models.CharField(default='#EEEEEE', max_length=7),
        ),
    ]
