# Generated by Django 5.0.9 on 2024-11-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0040_recordtype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtype',
            name='front_page',
            field=models.BooleanField(default=False),
        ),
    ]
