# Generated by Django 5.0.9 on 2024-11-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0041_recordtype_front_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentrecord',
            options={'ordering': ['-date', '-pk'], 'verbose_name': 'Equipment Record', 'verbose_name_plural': 'Equipment Records'},
        ),
    ]
