# Generated by Django 5.0.9 on 2024-11-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0043_siteconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'ordering': ['name'], 'verbose_name_plural': 'site configurations'},
        ),
    ]
