# Generated by Django 5.0.6 on 2024-08-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initials',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
